### ISSUE TITLE
Running cou as no-interactive doesn't show progress

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#101]
When running cou with the command: `cou run --no-interactive`  it's not possible to see the progress. It would be good for the user if the cli shows what steps has already completed.

**Comment by agileshaw** [comment]
Currently there is progress indication for the entire execution stage (`Running cloud upgrade`) but not its sub-steps. This issue was already described in https://github.com/canonical/charmed-openstack-upgrader/issues/84. Closing this as a duplicate.
