### ISSUE TITLE
Enable support for s390x, armhf, and ppc64el architectures

### ISSUE THREAD

**Issue by agileshaw** [canonical/charmed-openstack-upgrader#107]
Currently COU snap can only be built for x86 and arm64; building for other architectures resulted in failure. It would be great if we can support all available architecture to align with OpenStack products.

**Comment by Pjack** [comment]
We are closing this issue due to its low priority. Caracal is the final version of Charmed OpenStack, so new features and significant refactoring are unlikely to be implemented.
