### ISSUE TITLE
Require OSD release should happen as a post upgrade of ceph-osd and not ceph-mon

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#122]
Currently, the COU is running `_get_change_require_osd_release_plan` as a post upgrade of ceph-mon, but this step should happen after upgrading ceph-osd (data plane).

Running before osd upgrade this issue happen:
```shell
sudo ceph osd require-osd-release pacific
Error EPERM: not all up OSDs have CEPH_FEATURE_SERVER_PACIFIC feature
```

**Comment by agileshaw** [comment]
After discussion will remove the `_get_change_require_osd_release_plan` from post_upgrade (and keep it in ceph-mon's pre_upgrade), and check osd version when setting the release
