### ISSUE TITLE
Be clear about which release we're upgrading from and to

### ISSUE THREAD

**Issue by aieri** [canonical/charmed-openstack-upgrader#129]
Although the plan is very clear about what's going to happen to the individual cloud components, we don't clarify what version the overall cloud is at, and which OpenStack release we're going to be upgrading to.

**Comment by agileshaw** [comment]
I implemented something that displays current and next cloud OS release ([PR#120](https://github.com/canonical/charmed-openstack-upgrader/pull/120/files#diff-e5cc2183ba957040fcefe3159399dc8f89b61edcef0ba57300fdfca6c30dd291R151-R152)). Currently this is only a part of analysis result and will not show unless verbose mode is turned on. I can add it to the plan and always display it (except in quiet mode) before the actual steps
