### ISSUE TITLE
Consider the cases where running command on unit fails is acceptable/expected

### ISSUE THREAD

**Issue by agileshaw** [canonical/charmed-openstack-upgrader#148]
With the changes introduced in [PR#130](https://github.com/canonical/charmed-openstack-upgrader/pull/130), we are always raising CommandRunFailed exception when result is with non-zero code. In some cases, we may expect a command could fail and handle it in code, so we should consider how to deal with that.

Currently, we are considering two possible approaches:
- add `raise_on_failure` param to `run_on_unit` function (with default to `True`). This way we are not always raising exception.
- change `CommandRunFailed` exception to allow public access to `stdout` and `stderr` attribute. With this approach, the calling function can catch the exception with easier access to parts of the result.

**Comment by aieri** [comment]
we don't know at the moment if we need to support xfail commands
