### ISSUE TITLE
Overhaul the version to codename mapping

### ISSUE THREAD

**Issue by aieri** [canonical/charmed-openstack-upgrader#15]
We currently resolve cloud component versions to OpenStack codenames using a modified version of zaza's `get_os_code_info` function. This issue tracks at least these improvements:
* since the mapping is applied to both core OpenStack components and auxiliary components (e.g. ceph, ovn), it should more appropriately named; we're basically returning the latest or the set of OpenStack versions a given component is compatible with
* all related code should live in the same place. The Application class should import the lookup function and call it without having to know its inner workings, i.e. `Application._get_representative_workload_pkg` and `Application._get_current_os_version` should disappear
* stop using regexps and use an external package for parsing versions
* don't just look at the major version. Horizon in particular can only be mapped checking if its version falls in a specific range: 17.0.0 to 18.3.5 is Ussuri, while Victoria starts at 18.4
* keep in mind all of this should eventually become an external package. Everything should be self-contained

**Comment by gabrielcocenza** [comment]
Closed by #16
