### ISSUE TITLE
Top level plan should not require prompt

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-openstack-upgrader#150]
Currently the top level plan required interaction from user and that is redundant, because no functions trigger this step. 

The example of unnecessary prompt for top level plan,
```bash
$ cou_rg run
...
                        Upgrade 'octavia-diskimage-retrofit' to the new channel: 'victoria/stable'

Top level plan (c)ontinue/(a)bort/(s)kip:c
backup mysql databases (c)ontinue/(a)bort/(s)kip:c
...
```

**Comment by agileshaw** [comment]
This is a duplicate of https://github.com/canonical/charmed-openstack-upgrader/issues/128. Closing the issue.
