### ISSUE TITLE
wait_for_idle is not enough to validate that upgrade was finished

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-openstack-upgrader#161]
Cou finished all upgrade steps for placement or octavia, but it failed on checking workload status. This happen when all units were in idle state meaning that it should be fine to continue.

Examples:
```bash
Check if the workload of 'placement' has been upgraded (c)ontinue/(a)bort/(s)kip:c
Generating upgrade plan... ✖
2023-11-02 16:49:45 [ERROR] Cannot upgrade units 'placement/1' to wallaby.
```

```bash
Change charm config of 'octavia' 'openstack-origin' to 'cloud:focal-wallaby' (c)ontinue/(a)bort/(s)kip:c
Wait 120 s for app octavia to reach the idle state. (c)ontinue/(a)bort/(s)kip:s
Check if the workload of 'octavia' has been upgraded (c)ontinue/(a)bort/(s)kip:c
Generating upgrade plan... ✖                                                                             
2023-11-02 19:08:19 [ERROR] Cannot upgrade units 'octavia/0, octavia/1, octavia/2' to wallaby.
```

it's possible that we need to make check of workload status with timeout, so we can wait until units really settle.

**Comment by gabrielcocenza** [comment]
This is happening for all reactive charms, so it’s not a COU issue. We can try to implement some workaround like trying to run the openstack-upgrade action, but this is a dirty fix.

We can open a bug to have a workaround like running openstak-upgrade when this is detecte.

See [#2039604](https://bugs.launchpad.net/charm-barbican/+bug/2039604) for more context about the bug and possible workaround
