### ISSUE TITLE
COU should deal with Deferred service events

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#212]
The deferred service events feature allows the operator the choose to prevent these service restarts and hook calls from occurring. 

COU need to check before upgrading and after upgrading if the following charms has deferred-events to run:

List of charms that can have this:
- [neutron-gateway](https://opendev.org/openstack/charm-neutron-gateway/src/branch/master/README.md#deferred-service-events)
- [neutron-openvswitch](https://opendev.org/openstack/charm-neutron-openvswitch/src/branch/master/README.md#deferred-service-events)
- [ovn-central](https://opendev.org/x/charm-ovn-central/src/branch/master/README.md#deferred-service-events)
- [ovn-chassis](https://opendev.org/x/charm-ovn-chassis/src/branch/master/README.md#deferred-service-events)
- [ovn-dedicated-chassis](https://opendev.org/x/charm-ovn-dedicated-chassis/src/branch/master/README.md#deferred-service-events)
- [rabbitmq-server](https://opendev.org/openstack/charm-rabbitmq-server/src/branch/master/README.md#deferred-service-events)

**Comment by Pjack** [comment]
1. Support rabbitmq: https://github.com/canonical/charmed-openstack-upgrader/pull/413

2. According to the discussion with ovn team, the correct way of handling ovn-{chassis,dedicated-chassis,central} charms is outlined in the upstream documentation: [OVN Upgrades — Open Virtual Network (OVN) 24.03.90 documentation](https://docs.ovn.org/en/latest/intro/install/ovn-upgrades.html#rolling-upgrade) . In terms of the upgrade for the ovn charms, as long as the ovn-{chassis,dedicated-chassis} is upgraded before ovn-central, and with enable-auto-restart=True and enable-version-pinning=False the rolling upgrades is automatically supported by the charm / ovn-* itself. This means that supporting enable-auto-restart=False is unnecessary, and only complicates the upgrade process of ovn charms.

In Cou, it will block the user if `enable-auto-restart=True and enable-version-pinning=False` is not True
