### ISSUE TITLE
Manually deployed version of charm cause COU failure

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-openstack-upgrader#256]
If you tried to run COU against model with any manually build charm, you will see something like this.
```bash
$ cou plan
...
File "/snap/charmed-openstack-upgrader/x7/lib/python3.10/site-packages/cou/apps/base.py", line 208, in _get_track_from_channel
    return charm_channel.split("/", maxsplit=1)[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

We should catch this during planning stage and raise our own exception with better message.

**Comment by aieri** [comment]
we don't plan to support local charms at the moment
