### ISSUE TITLE
OpenStackApplication should handle the HaltUpgradePlanGeneration itself

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-openstack-upgrader#312]
We should handle the `HaltUpgradePlanGeneration` in the `generate_upgrade_plan` instead of outside with function like [`create_upgrade_group`](https://github.com/canonical/charmed-openstack-upgrader/blob/c3560aeb771dcef51f07c907e32382752b68bb40/cou/steps/plan.py#L117).

I believe that this will help improve the logic of the whole `HaltUpgradePlanGeneration` and how we handle it.

**Comment by aieri** [comment]
This should already be fixed
