### ISSUE TITLE
Remove .extend from steps

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#315]
With the addition of `add_steps` we should change the steps that are using `.extend` that can possibly add empty steps.

E.g on `hypervisors.py`

```python
hypervisor_plan.sub_steps.extend(self._generate_pre_upgrade_steps(target, group))
```
Should be changed to:
```python
hypervisor_plan.add_steps(self._generate_pre_upgrade_steps(target, group))
```

**Comment by rgildein** [comment]
This will be fixed by #328, so there is no need to do it. Thanks for trying to contribute.
