### ISSUE TITLE
COU should have a more clear way on deciding the upgrade strategy.

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#344]
Currently, `OpenStackApplication` class will upgrade using `all-in-one` strategy if no units are passed into `generate_upgrade_plan` and `pause-single-unit` if a list of units is passed.

I think the logic of choosing the upgrade strategy should be part of a higher level of the software like on planing and passed to the application and not let the application decide by units argument. I think this will make a better logic and responsibility separation

**Comment by gabrielcocenza** [comment]
This might also solve the problem of what was [spotted](https://github.com/canonical/charmed-openstack-upgrader/pull/337#discussion_r1542678154) by @rgildein on checking units might behave differently if an empty list is passed

**Comment by Pjack** [comment]
Close this JIRA ticket. 
Refactoring has become a low priority, as Caracal will be the final release of charmed-openstack.
