### ISSUE TITLE
The `can_upgrade_to` for application should be something like `ch:amd64/focal/nova-compute-723 `

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-openstack-upgrader#350]
Currently, in our unit tests we are using channel name for `can_upgrade_to` instead of charmhub address, e.g. `ch:amd64/focal/nova-compute-723 `.
This is not causing any issue in code, since we are only checking if values is empty, but it would be good to replace all those values in all unit tests.

**Comment by samuelallan72** [comment]
@rgildein can you explain why this is an issue?  What is the purpose of `can_upgrade_to` used in the application code?  It's not documented, and it's only ever used as a boolean value.

**Comment by rgildein** [comment]
Yes we are checking only if there is any value, without checking the context of value. The issue is that right now if you open our unit tests, you can wrongly assume that the value should be `latest/edge` instead of full address, e.g. `ch:amd64/focal/nova-compute-723`

Currently, this does not cause any issue, and potentially it will never cause any issue, but it is misguiding.

**Comment by samuelallan72** [comment]
Got it - you mean that the mocked values don't match what would be seen in reality?

**Comment by Pjack** [comment]
Close this JIRA ticket. 
Refactoring has become a low priority, as Caracal will be the final release of charmed-openstack.
