### ISSUE TITLE
Consider using "Parametrizing fixtures" for sample_plans fixtures in mocked-plans tests

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-openstack-upgrader#356]
In original #334 introducing the mocked-plans, we discuss that maybe it would be good to use [Parametrizing fixtures](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#parametrizing-fixtures) for sample_plans fixture.
Like this each test will run for each yaml file, what can be an issue if we want to create custom tests (e.g. just for one hypervisor or with some hypervisors not being empty).

**Comment by Pjack** [comment]
Refactoring has become a low priority, as Caracal will be the final release of charmed-openstack.
