### ISSUE TITLE
Expand usage of `--force`

### ISSUE THREAD

**Issue by agileshaw** [canonical/charmed-openstack-upgrader#369]
Right now `--force` is only used for including non-empty hypervisors in the upgrade, but we can expand its usage: making it a way for user to give consent to COU to perform potentially disruptive actions.

An example would be how we can handle upgrades for a charm with current channel of `latest/stable`. Currently we are automatically switching it to a release-based channel, but since this may be a downgrade, it is not considered a safe operation. An improvement would be to raise a warning when `latest/stable` channel is detect and refuse upgrade unless the user passes in the `--force` option to indicate that they _really_ want to continue the upgrade. Of course we need to make sure to give user clear instructions on this.

**Comment by aieri** [comment]
this is very low priority, closing for now
