### ISSUE TITLE
If upper, lower and compared versions are same it returns false

### ISSUE THREAD

**Issue by esunar** [canonical/charmed-openstack-upgrader#37]
https://github.com/canonical/charmed-openstack-upgrader/blob/a4101a6972c1191628d95d1b24e2246a632054b5/cou/utils/openstack.py#L244

For example:

```
arr = [VersionRange("6.0.0", "6.0.0")]
if "6.0.0" in arr:
    print("I am in range")
else:
    print("I am not in range")

```

**Comment by gabrielcocenza** [comment]
I'm not entirely sure if this is a bug or if it's a misusage of the `VersionRange` class. The `upper` it's not meant to be inclusive.
I think we should raise an error if someone tries to instantiate a VersionRange with the same value for `upper` and `lower`.
@aieri what is your point of view on this?

**Comment by aieri** [comment]
the idea was to model `range()`, and the described behavior is consistent:
```
In [4]: r = range(5,5)

In [5]: 5 in r
Out[5]: False
```

I'm open to raising an error if upper == lower if you prefer.
