### ISSUE TITLE
The plan for ceph-osd disappears after upgrading hypervisors

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#380]
Auxiliary charms, like ceph-osd, when called to give the current OpenStack release will always answer with the highest compatible one. That means if the workload_version is running `octopus`, it's compatible with `Ussuri` and `Victoria` and the application will say that is `Victoria`. If all OpenStack components are already upgraded to `Victoria`, ceph-osd will stop generating a plan to change the `source` to `cloud:focal-victoria` and will start generating the plan for `Wallaby` changing the `source` from `distro` directly to `cloud:focal-wallaby`. Although there is no change in the package version between ussuri to victoria, this is not consistent and can confuse users because they would see a ceph plan using `cou plan` and wouldn't see after upgrading all hypervisors

**Comment by chanchiwai-ray** [comment]
@gabrielcocenza this was mentioned in and fixed by PR: #400, can you confirm that this issue is still valid or not
