### ISSUE TITLE
ceph-mon is failing to show the right version of osd and this can be problematic

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#401]
For some unknown reason, after upgrading all ceph-osds to `pacific` on partner cloud, ceph-mon still says that osd's are on `octopus`. 

E.g:
```
{
    "mon": {
        "ceph version 16.2.14 (238ba602515df21ea7ffc75c88db29f9e5ef12c9) pacific (stable)": 3
    },
    "mgr": {
        "ceph version 16.2.14 (238ba602515df21ea7ffc75c88db29f9e5ef12c9) pacific (stable)": 3
    },
    "osd": {
        "ceph version 15.2.17 (8a82819d84cf884bd39c17e3236e0632ac146dc4) octopus (stable)": 18
    },
    "mds": {},
    "rgw": {
        "ceph version 15.2.17 (8a82819d84cf884bd39c17e3236e0632ac146dc4) octopus (stable)": 3
    },
    "overall": {
        "ceph version 15.2.17 (8a82819d84cf884bd39c17e3236e0632ac146dc4) octopus (stable)": 21,
        "ceph version 16.2.14 (238ba602515df21ea7ffc75c88db29f9e5ef12c9) pacific (stable)": 6
    }
}
```

This is problematic because it pass the `set_require_osd_release_option` once that the ` require-osd-release` is also on `octopus`and this will let the cloud continue upgrading. I guess the right thing is to halt the execution if we see that there is more than one ceph version in the cloud.

**Comment by gabrielcocenza** [comment]
After rebooting a ceph-osd machine (not necessary) and restarting the services using `sudo systemctl restart ceph.target`, ceph-osd versions got updated like in the payload:

```
{
    "mon": {
        "ceph version 16.2.14 (238ba602515df21ea7ffc75c88db29f9e5ef12c9) pacific (stable)": 2,
        "ceph version 16.2.15 (618f440892089921c3e944a991122ddc44e60516) pacific (stable)": 1
    },
    "mgr": {
        "ceph version 16.2.14 (238ba602515df21ea7ffc75c88db29f9e5ef12c9) pacific (stable)": 2,
        "ceph version 16.2.15 (618f440892089921c3e944a991122ddc44e60516) pacific (stable)": 1
    },
    "osd": {
        "ceph version 16.2.15 (618f440892089921c3e944a991122ddc44e60516) pacific (stable)": 18
    },
    "mds": {},
    "rgw": {
        "ceph version 15.2.17 (8a82819d84cf884bd39c17e3236e0632ac146dc4) octopus (stable)": 2,
        "ceph version 16.2.14 (238ba602515df21ea7ffc75c88db29f9e5ef12c9) pacific (stable)": 1
    },
    "overall": {
        "ceph version 15.2.17 (8a82819d84cf884bd39c17e3236e0632ac146dc4) octopus (stable)": 2,
        "ceph version 16.2.14 (238ba602515df21ea7ffc75c88db29f9e5ef12c9) pacific (stable)": 5,
        "ceph version 16.2.15 (618f440892089921c3e944a991122ddc44e60516) pacific (stable)": 20
    }
}
```

`rgw` had the same issue as `osd`

**Comment by valexby** [comment]
Hi, also was affected by this one during Octopus -> Pacific upgrade of `ceph-osd` during the last step of Victoria -> Wallaby upgrade. Reported [ceph-osd charm LP2068151 bug](https://bugs.launchpad.net/charm-ceph-osd/+bug/2068151) also, as it is not clear why charm hasn't done any restarts.

**Comment by samuelallan72** [comment]
> I guess the right thing is to halt the execution if we see that there is more than one ceph version in the cloud.

I'm looking into this, and adding a pre-upgrade sanity check for this is not as simple as it seems, as there is a lot to consider:

- How do we handle the case where there are multiple ceph-osd applications related? 
  - If cou was restarted in the middle of an upgrade, one ceph-osd may be upgraded but not the other yet.
- If cou was restarted in the middle of an upgrade, it's normal that there may be mismatched versions, so we'd need to compare the output from ceph-mon `ceph versions` with the channel and workload versions of related ceph applications.

Maybe I'm over-engineering this, but it's looking like it's going to be tricky to get it right for all cases. And if we're talking about a blocking error, then we need to get it right for all cases to avoid blocking a cloud upgrade unnecessarily.

Perhaps we can go with something much simpler:

- Check for mismatched versions from ceph-mon `ceph versions`.
- If any mismatched versions, output a warning (nonblocking) to the user with the details, recommending they only continue the upgrade if this is expected.
- Do the above pre and post upgrade.

Thoughts?
