### ISSUE TITLE
Add sanity check for series

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#403]
As described by @aieri  in this [comment](https://github.com/canonical/charmed-openstack-upgrader/pull/400#discussion_r1588291994) it's weird having a property that can raise `ApplicationError` because the series is not supported. This should happen during the class instantiation, probably at a sanity check. After that we can access directly, without the concern of raising exception like `KeyError`

**Comment by Pjack** [comment]
Close this JIRA ticket. 
Refactoring has become a low priority, as Caracal will be the final release of charmed-openstack.
