### ISSUE TITLE
OpenStackRelease class accepting cloud:<ubuntu_series>-<o7k_release> syntax 

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#404]
As mentioned by @aieri in this [comment](https://github.com/canonical/charmed-openstack-upgrader/pull/400#discussion_r1588291994), it would be nice to have the OpenStackRelease also accepting inputs like: `cloud:focal-yoga`

**Comment by Pjack** [comment]
Close this JIRA ticket. 
Refactoring has become a low priority, as Caracal will be the final release of charmed-openstack.
