### ISSUE TITLE
Investigate when or should we use `self.model.config.get`

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/charmed-openstack-upgrader#426]
As per this [comment](https://github.com/canonical/charmed-openstack-upgrader/pull/413#discussion_r1618336933), there is possibility that some config options are no available in all versions, using `self.model.config[]` directly might cause `KeyError`, we should investigate more on when or should we use `self.model.config.get` to perform safer dict operations.

As of this commit: 64b72ee72763f717ca7917a5f3f2d8792d133d01

we have the following places use this pattern:

```python
cou/apps/base.py:113:                    key: self.config[key] for key in self.config if key in REQUIRED_SETTINGS
cou/apps/base.py:239:            return self.config[origin].get("value", "")
cou/apps/base.py:696:        amu_config = self.config["action-managed-upgrade"].get("value")
cou/apps/base.py:858:        if self.config["enable-auto-restarts"].get("value") is False:
cou/apps/auxiliary.py:361:        if self.config["enable-version-pinning"].get("value"):
```

**Comment by chanchiwai-ray** [comment]
Or better yet, just do it since it's just a few places need changing

**Comment by rgildein** [comment]
This is not true, since all these examples are properly checking the config before accessing the key.
