### ISSUE TITLE
Improve docs for `enable-version-pinning` config constraint

### ISSUE THREAD

**Issue by samuelallan72** [canonical/charmed-openstack-upgrader#460]
I observed this on a cloud with `enable-version-pinning` set to true for octavia-ovn-chassis and ovn-chassis.  COU plan/upgrade emits this error output:

```
Cannot generate plan for 'octavia-ovn-chassis'
        Cannot upgrade 'octavia-ovn-chassis'. 'enable-version-pinning' must be set to 'false'.
Cannot generate plan for 'ovn-chassis'
        Cannot upgrade 'ovn-chassis'. 'enable-version-pinning' must be set to 'false'.
```

I couldn't find the reason why it must be set to false, and I couldn't find any recommendation for what to do now (is it safe to set the config to false on a production cloud?).

We should improve the docs here.

**Comment by Pjack** [comment]
An idea is to implement a `cou lint` command to check the environment and print out detail information.
