### ISSUE TITLE
Ceph 'channels supported during transition' message is confusing

### ISSUE THREAD

**Issue by samuelallan72** [canonical/charmed-openstack-upgrader#461]
It's confusing what this message means, and what is actually supported:

```
2024-06-27 06:04:27 [cou.cli] [WARNING] Cannot generate plan for 'ceph-mon'
        The 'ceph-mon' application is using channel 'quincy/stable'. Channels supported during this transition: 'octopus/stable', 'octopus/stable'. Manual intervention is required.
Cannot generate plan for 'ceph-radosgw'
        The 'ceph-radosgw' application is using channel 'quincy/stable'. Channels supported during this transition: 'octopus/stable', 'octopus/stable'. Manual intervention is required.
Cannot generate plan for 'ceph-osd'
        The 'ceph-osd' application is using channel 'quincy/stable'. Channels supported during this transition: 'octopus/stable', 'octopus/stable'. Manual intervention is required.
```

Note the repetition: `'octopus/stable', 'octopus/stable'` - I think this is a bug, and this is supported by the comment in the tests (the comment mentions octopus and pacific, but the asserted message has the double octopus).

https://github.com/canonical/charmed-openstack-upgrader/blob/3202265ea3e24b788245d46976c6468babb48039/tests/unit/apps/test_auxiliary.py#L1581-L1586

Also the message could be clearer - it's supposed to be an error that there are no upgrade paths supported for that release (and maybe that it's unexpected to see ceph quincy on a ussuri openstack cloud?).  But it talks about transitions and unspecified manual intervention.

**Comment by Pjack** [comment]
It happens when we want to downgrade the environment which is not common.
