### ISSUE TITLE
[cinder / cinder-ceph] upgrading `cinder` will cause its subordinate `cinder-ceph` to failed on relation changed

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/charmed-openstack-upgrader#466]
```
Wait for up to 300s for app 'cinder' to reach the idle state ✖
2024-06-24 04:45:08 [ERROR] Timed out waiting for model:
  cinder/0 [executing] maintenance: Running openstack upgrade
2024-06-24 04:45:08 [ERROR] See the known issues at https://canonical-charmed-openstack-upgrader.readthedocs-hosted.com/en/stable/reference/known-issues/
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed Traceback (most recent call last):
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed   File "/var/lib/juju/agents/unit-cinder-ceph-0/charm/charmhelpers/core/strutils.py", line 94, in __init__
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed     self.index = self._list.index(item)
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed ValueError: tuple.index(x): x not in tuple
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed During handling of the above exception, another exception occurred:
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed Traceback (most recent call last):
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed   File "/var/lib/juju/agents/unit-cinder-ceph-0/charm/hooks/storage-backend-relation-changed", line 469, in <module>
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed     hooks.execute(sys.argv)
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed   File "/var/lib/juju/agents/unit-cinder-ceph-0/charm/charmhelpers/core/hookenv.py", line 963, in execute
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed     self._hooks[hook_name]()
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed   File "/var/lib/juju/agents/unit-cinder-ceph-0/charm/hooks/storage-backend-relation-changed", line 348, in storage_backend_changed
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed     storage_backend()
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed   File "/var/lib/juju/agents/unit-cinder-ceph-0/charm/hooks/storage-backend-relation-changed", line 320, in storage_backend
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed     subordinate_config = CephSubordinateContext()()
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed   File "/var/lib/juju/agents/unit-cinder-ceph-0/charm/hooks/cinder_contexts.py", line 71, in __call__
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed     if CompareOpenStackReleases(os_codename) >= "icehouse":
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed   File "/var/lib/juju/agents/unit-cinder-ceph-0/charm/charmhelpers/core/strutils.py", line 96, in __init__
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed     raise KeyError("Item '{}' is not in list '{}'"
unit-cinder-ceph-0: 05:24:20 WARNING unit.cinder-ceph/0.storage-backend-relation-changed KeyError: "Item 'zed' is not in list '('diablo', 'essex', 'folsom', 'grizzly', 'havana', 'icehouse', 'juno', 'kilo', 'liberty', 'mitaka', 'newton', 'ocata', 'pike', 'queens', 'rocky', 'stein', 'train', 'ussuri', 'victoria', 'wallaby', 'xena', 'yoga')'"
```

**Environment**: OpenStack deployed by stsstack-bundle: `./generate-bundle.sh --name cou -r yoga -s jammy --ceph --run`

**Step to reproduce**: you can run `cou upgrade` on the environment mentioned above. Or do it manually following the `cou plan` 

```
juju refresh cinder --channel zed/stable
juju config cinder openstack-origin=source:jammy-zed
# and wait until this error happens
```

If the we ignore the error in `cinder-ceph`, and force upgrading `cinder-ceph`

```
juju refresh cinder-ceph --channel zed/stable
```

The error in `cinder-ceph` will go away.

**Relevant information**:

- “zed” was not presented during upgrade: https://opendev.org/openstack/charm-cinder-ceph/src/branch/stable/yoga/charmhelpers/fetch/ubuntu.py#L250 

- “zed“ exists after the upgrade: https://opendev.org/openstack/charm-cinder-ceph/src/branch/stable/zed/charmhelpers/fetch/ubuntu.py#L263 

**Note**: This happens on a openstack cloud delpoyed by [stsstack-bundle](https://github.com/canonical/stsstack-bundles), and it happens for upgrading from **Jammy/Yoga or above** .

**Comment by jneo8** [comment]
I somehow think this is not the issue we can handle in the charm.

The options we can have is either:

1. Handle two applications' upgrade together.
2. Ignore the status of cinder-ceph until we run the upgrade for it.


For me option 2 is too tricky.

@gabrielcocenza Is there is a way I can combine those two apps' upgrade together?

**Comment by jneo8** [comment]
### Possible solution 1: Make sure the upgrading is in right order

We make sure the order of the upgrading is been followed, for example. The cinder-ceph is always upgrade after cinder. And remove the checking of cinder-ceph's status in cinder upgrading. So it's like a series of steps to upgrade both cinder and cinder-ceph.

### Possible solution 2:

We decouple the `steps` and `application` logic in `OpenStackApplication`.
A class to generate the upgrade steps shouldn't belong to one single application.
This may need a lot of refactor and a lot of cou plan logic need to be re-created.

**Comment by gabrielcocenza** [comment]
We should take care to not try to cover all the issues doing workarounds on COU.
There are issues on the charms itself and this looks like one of then. If you see the latest version of [charmhelpers](https://github.com/juju/charm-helpers/blob/master/charmhelpers/fetch/ubuntu.py#L294-L321) zed is there but looking at the  [yoga/stable](https://opendev.org/openstack/charm-cinder-ceph/src/branch/stable/yoga/charmhelpers/fetch/ubuntu.py#L254-L277) branch the list is not updated, so it seems that is a simple update on charmhelpers will fix that

**Comment by jneo8** [comment]
The message from @ajkavanagh:

>  In general subordinates probably should be switched to the next OpenStack track before the principle charm, as the 'next' track always supports the current track.  However, charms come from different eras, and the latest charms that were subordinates tried very hard not to 'upset' the principle.  Older charms could be a bit hit and miss.  In general, I'd still say that subordinates should have their track switched first, followed by principle charms.

The easiest way to resolve the issue maybe reverse the order of upgrading now, we upgrade subordinate first then principle.

**Comment by jneo8** [comment]
The issue to trace document updating: [OpenStack upgrade advice around subordinates and principle charms needs to be updated [Edit](https://bugs.launchpad.net/charm-guide/+bug/2072311/+edit)

**Comment by samuelallan72** [comment]
After reading https://docs.openstack.org/project-deploy-guide/charm-deployment-guide/yoga/upgrade-overview.html#channels more, it makes sense that subordinate charms must be refreshed to the target release before upgrading principle charms.

> With the channels type, a channel is dedicated to a single OpenStack release (release N-1 will be technically supported to assist with upgrades).

In this case, the situation begins with:

- cinder yoga/stable (officially supporting yoga and xena) running on yoga release
- cinder-ceph yoga/stable (officially supporting yoga and xena) running on yoga release

After upgrading cinder completely (refresh to new channel + update openstack-origin config), the situation is:

- cinder zed/stable (officially supporting zed and yoga) running on zed release
- cinder-ceph yoga/stable (officially supporting yoga and xena) running on zed release

So immediately cinder-ceph is running on an unsupported release base.

I agree that the documentation must be updated as described in [LP: #2072311](https://bugs.launchpad.net/charm-guide/+bug/2072311).

Something else that isn't clear is whether all charms should be refreshed to the target release channel, then the actual upgrades happen?  As in, instead of the current situation:

- juju refresh X --channel zed/stable
- juju config X openstack-origin=cloud:jammy-zed
- juju refresh Y --channel zed/stable
- juju config Y openstack-origin=cloud:jammy-zed
- juju refresh Z --channel zed/stable
- juju config Z openstack-origin=cloud:jammy-zed

We could do:

- juju refresh X --channel zed/stable
- juju refresh Y --channel zed/stable
- juju refresh Z --channel zed/stable
- juju config X openstack-origin=cloud:jammy-zed
- juju config Y openstack-origin=cloud:jammy-zed
- juju config Z openstack-origin=cloud:jammy-zed

I wonder what's best

**Comment by ajkavanagh** [comment]
The general approach would be, for a single machine.

a) Make sure all the charms are up to date for their channel first.  `juju refresh`
b) Make sure that openstack-origin/source is pointing to the current version (i.e. is not the 'default' unset state). 
c) Switch charms to the next channel (subordinates and principles) - `juju switch`
d) Switch the openstack-origin/source of the principle charms `juju config` (and perhaps `juju run ... openstack-upgrade`.

This would ensure the best chance of success.  I think with this approach, any errors are then a bug that should be fixed.
