### ISSUE TITLE
[vault] newer version stopping cou plan/upgrade

### ISSUE THREAD

**Issue by honghan-wong** [canonical/charmed-openstack-upgrader#472]
When we are running cou on some clouds on ussuri, the vault charm is running on a later version `1.10.6`. 

The current cou is allow only vault version `1.7` on ussuri version.

Is it possible to have cou support some charms where a later version will not cause incompatible between openstack components?

Example is vault `1.10.6` doesn't introduce breaking change and should be able to support the upgrade between ussuri and yoga.
If the vault is on a later version, cou might be able to skip the upgrade for vault.

**Comment by jneo8** [comment]
A very quick option is to update `cpu/utils/openstack_to_track mapping.csv` from your expectation.

A more general option is that we we provide `--skip-apps` argument for the user to skip the upgrade steps for some application.

**Comment by gabrielcocenza** [comment]
One thing that it's not clear to me is why the vault is using `1.10`. By the charm [page](https://charmhub.io/vault) seems that we don't have this option on channels. @honghan-wong what is the channel  that the charm is using?

**Comment by honghan-wong** [comment]
vault charm is using rev `54`, channel `latest/stable`
```
vault                     1.10.6   active      3  vault                     latest/stable   54  no       Unit is ready (active: true, mlock: enabled)
```

We have met issue before on vault charm where the snap has refreshed the vault to a later version and triggered an alert from nrpe check mentioning version mismatch.
To solve it, we have to restart the vault service and the charm will refreshed to the later version.
And I believe this is one of the case, where the charm is on an older revision but vault has upgrade to a later version.

**Comment by aieri** [comment]
@honghan-wong you're also using the `latest/stable` track, which is closed. The charm should be switched to track `1.7/stable`. I don't know if you can downgrade the vault snap without breakages though.

**Comment by samuelallan72** [comment]
An option is to add some kind of ignore flag, along the lines of https://github.com/canonical/charmed-openstack-upgrader/issues/478 .  Then if it's not possible on a cloud to switch the charm or workload to something recognised by COU, and the engineer upgrading the cloud determines that it's fine, they can tell cou to ignore or skip it.

**Comment by jneo8** [comment]
Proposal to skip +1

We can have a CLI argument to skip vault upgrading.
