### ISSUE TITLE
COU should be more obvious when it's not going to upgrade nova-compute

### ISSUE THREAD

**Issue by samuelallan72** [canonical/charmed-openstack-upgrader#480]
This is the top of the output of running an upgrade with cou where there hypervisors are non-empty:

```
$ cou upgrade --auto-approve
Full execution log: '/home/ubuntu/.local/share/cou/log/cou-20240703060236.log'
Connected to 'openstack' ✔
Analyzing cloud... ✔
Generating upgrade plan... \2024-07-03 06:02:54 [WARNING] Not changing the install repository of app designate-bind: None already set to cloud:focal-victoria
Generating upgrade plan... /2024-07-03 06:03:01 [WARNING] Found non-empty hypervisors: [nova-compute/0, nova-compute/1, nova-compute/2, nova-compute/3, nova-compute/4]
Generating upgrade plan... ✔
Upgrade cloud from 'ussuri' to 'victoria'
        Verify that all OpenStack applications are in idle state
        Back up MySQL databases
...
  ```

It's not clear that the warning about finding non-empty hypervisors means that cou will skip upgrading these nova-compute units.  It simply states that it found non-empty hypervisors and doesn't not give any further information.

It should be much clearer.  Especially as this then blocks future steps, as some further steps require hypervisors to be upgraded.

**Comment by rgildein** [comment]
Agreed that warning message could be improved and I approve your PR.
