### ISSUE TITLE
Unclear what "running mismatched openstack versions" means

### ISSUE THREAD

**Issue by samuelallan72** [canonical/charmed-openstack-upgrader#487]
For example:

```
2024-07-09 07:40:05 [WARNING] Cannot generate plan for 'aodh'
        Units of application aodh are running mismatched OpenStack versions: 'victoria': ['aodh/0'], 'wallaby': ['aodh/1', 'aodh/2']. This is not currently handled.
```

It would be good to output more information at a lower level to help with debugging:

- which packages/services were tested for version, and how they were tested
- what the expected version ranges were
- what the actual version ranges are

**Comment by samuelallan72** [comment]
@gabrielcocenza @rgildein @jneo8 @chanchiwai-ray is there any disadvantage to checking directly for mismatched __workload__ versions instead? Then we can be clearer in the error message, by referencing the actual workload versions.

**Comment by jneo8** [comment]
> Are there any cases where workload versions may be mismatched, but the relevant openstack release is still the same (eg. if the versions were 21.0.1 and 21.0.2, only differing by a patch release)? Is it ok if workload versions are mismatched at all?

This shouldn't happen and can be danger.

> Thoughts on this design?

Nice and clear, +1 for it.
And can we also output the expected version?

**Comment by gabrielcocenza** [comment]
> Are there any cases where workload versions may be mismatched, but the relevant openstack release is still the same (eg. if the versions were 21.0.1 and 21.0.2, only differing by a patch release)? Is it ok if workload versions are mismatched at all?

This is not suppose to happen. We are using the [packaging](https://github.com/pypa/packaging) lib and in the openstack_lookup.csv we add the lower and upper version (not inclusive).
So for aodh, for example, it's considered as victoria: 11.0.0 <= pkg_version <  12.0.0

We consider mismatched regarding o7k releases map and not the fine grained version itself. So 11.0.0 and 11.9.9 is Victoria and don't have mismatched versions

**Comment by samuelallan72** [comment]
Thanks for your comments. :)
