### ISSUE TITLE
[Refactor] The planner class

### ISSUE THREAD

**Issue by jneo8** [canonical/charmed-openstack-upgrader#496]
Now the architecture of `Hypervisor`, `OpenstackAppliction` are coupling with the functions to generate the steps.

I would like to open a proposal to refactor this part by define a `Planner` abstract class and inherit by both `Hypervisor` and `OpenstackApplication`.

The `steps` package shouldn't know the details of Hypervisor and OpenstackApplication, the only things provides to `steps` will be only `Step` and `Planner`.

**Comment by Pjack** [comment]
Close this JIRA ticket. 
Refactoring has become a low priority, as Caracal will be the final release of charmed-openstack.
