### ISSUE TITLE
Upgrade strategy for data-plane review

### ISSUE THREAD

**Issue by jneo8** [canonical/charmed-openstack-upgrader#511]
Relate to #468, #501 #503

There are three major rules we want to have:

1. Upgrade subordinate before principle on the same machine to avoid bug: #468
2. Merge principle & subordinate applications upgrade into hypervisor.
3. The upgrade order shouldn't be broken in any situation.

We need to go through all the data plane applications to make sure upgrade strategy for all of them and apply to COU.

**Comment by Pjack** [comment]
These three issues have been resolved, so I am closing this discussion.
