### ISSUE TITLE
mysql-innodb-cluster source configuration need to be distro after yoga.

### ISSUE THREAD

**Issue by jneo8** [canonical/charmed-openstack-upgrader#523]
The newest version of mysql-innodb-cluster charm is built against the stable/yoga version of charm-helpers. The reason is because we don't tend to carry mysql package in the cloud archive, so in practice using `distro` or `cloud:jammy-antelope` will result in exactly the same mysql payload version.

**Comment by chanchiwai-ray** [comment]
It's working fine for me

```
juju deploy mysql-innodb-cluster -n 3 --channel 8.0/stable
juju config mysql-innodb-cluster source=cloud:jammy-zed 
juju config mysql-innodb-cluster source=cloud:jammy-antelope
```

**Comment by jneo8** [comment]
What is your mysql version and charm-helper version?

**Comment by chanchiwai-ray** [comment]
revision ` 153 `

**Comment by jneo8** [comment]
I can't reproduce this one. So closed.
