### ISSUE TITLE
[Bug] Unnecessary step for supported app with zero units.

### ISSUE THREAD

**Issue by jneo8** [canonical/charmed-openstack-upgrader#549]
In the case that I have `cinder-ceph` application on the juju model, which is a subordinate charm but not relate to any principle so the unit number is zero. COU will still wait for it to become idle status but it's not possible. I suggest COU skip this unnecessary step.

**Comment by samuelallan72** [comment]
Would it make sense to set wait_for_at_least_units=0 to wait_for_idle? This would be a quick fix and I reckon would solve it for us.

It would be nice to add a step to the initial verify_cloud step too, to check for applications that have zero units.

**Comment by samuelallan72** [comment]
If we add `wait_for_at_least_units=0` to the `wait_for_idle` calls, this is not an issue - see https://github.com/canonical/charmed-openstack-upgrader/pull/564 .
