### ISSUE TITLE
openstack-dashboard is upgraded out of order

### ISSUE THREAD

**Issue by samuelallan72** [canonical/charmed-openstack-upgrader#555]
See https://docs.openstack.org/charm-guide/latest/admin/upgrades/openstack.html#list-the-upgrade-order - openstack-dashboard must be upgraded after nova-compute and before ceph-osd.  However cou currently puts it in the 'control-plane' group, and upgrades it before nova-compute.

**Comment by Pjack** [comment]
Based on the message in
https://github.com/canonical/charmed-openstack-upgrader/issues/554
We've confirmed with the OpenStack team that this order is acceptable too.

Closing this issue.
