### ISSUE TITLE
[Bug] Wait for model idle stuck forever if there are zero unit subordinate application

### ISSUE THREAD

**Issue by jneo8** [canonical/charmed-openstack-upgrader#559]
In the case: 

If there are subordinate application which not relate to any principle, which will have zero units, and we call [juju model wait_for_idle function](https://github.com/juju/python-libjuju/blob/50b42d013aee01536416e6334f99443f2b4f1e4c/juju/model.py#L2792) with no application filter, it will stuck forever because the check will never pass. 

Relate to: #549

**Comment by samuelallan72** [comment]
Would it make sense to set wait_for_at_least_units=0 to wait_for_idle? This would be a quick fix and I reckon would solve it for us.

It would be nice to add a step to the initial verify_cloud step too, to check for applications that have zero units.
