### ISSUE TITLE
[Bug/Antelope] openstack-dashboard workload version 23.2.0 has no compatible OpenStack release

### ISSUE THREAD

**Issue by jneo8** [canonical/charmed-openstack-upgrader#560]
Encounter on: `zed` -> `antelope`, step openstack-dashobard upgrade.

Error message:

```
cou.exceptions.ApplicationError: 'openstack-dashboard' with workload version 23.2.0 has no compatible OpenStack release.
```

The workload version for openstack-dashobard is `23.2` and not in the range antelope supported. Also the workload version on the [official document](https://docs.openstack.org/releasenotes/horizon/2023.1.html) is `23.1.0`.

Need to confirm which workload version is correct.

**Comment by samuelallan72** [comment]
I did some more digging, and I think the official pages to reference are:

- https://releases.openstack.org/antelope/index.html#antelope-horizon : compatible releases of horizon for antelope are 23.1.0 and 23.1.1
- https://releases.openstack.org/bobcat/index.html#bobcat-horizon : compatible releases of horizon for bobcat are 23.2.0 and 23.3.0

The openstack-dashboard charm however deploys:

- channel 2023.1/stable (antelope), default config, jammy: horizon 23.2.0
- channel 2023.1/stable (antelope), openstack-origin=cloud:jammy-antelope, jammy: horizon 23.2.0
- channel 2023.2/stable (bobcat), default config, jammy: horizon 23.3.0
- channel 2023.2/stable (bobcat), openstack-origin=cloud:jammy-bobcat, jammy: horizon 23.3.0

I've asked internally if this is expected.

If it's expected: we need to update COU's lookup table to include 23.2.0 in antelope,
If it's not expected: the charm and/or cloud archive ppa needs updating to install the correct version.

**Comment by samuelallan72** [comment]
> I've asked internally if this is expected.

Update: I was pointed to https://bugs.launchpad.net/cloud-archive/+bug/2030514 , where 23.2.0 was added to the antelope cloud archive ppa. Unsure if a decision was made to update to fix a bug, or if it was simply a mistake. But it may be there to stay.
