### ISSUE TITLE
[Bug/Caracal] openstack-dashboard workload version 24.0.0 has no compatible OpenStack release

### ISSUE THREAD

**Issue by jneo8** [canonical/charmed-openstack-upgrader#563]
Encounter on: `antelope` -> `Carcal`, step openstack-dashobard upgrade.

Error message:

```
cou.exceptions.ApplicationError: 'openstack-dashboard' with workload version 24.0.0 has no compatible OpenStack release.
```

Need to upgrade `openstack_lookup.csv` to support `24.0.0`

Reference: [offifical doc](https://docs.openstack.org/releasenotes/horizon/2024.1.html)

**Comment by samuelallan72** [comment]
Fixed by https://github.com/canonical/charmed-openstack-upgrader/pull/568
