### ISSUE TITLE
Checking if upgrade to target is successful should be dropped from plan output and be a mandatory part of the upgrade step itself

### ISSUE THREAD

**Issue by agileshaw** [canonical/charmed-openstack-upgrader#76]
A feedback from demo: 

Checking if an application has been successfully upgraded to a target release should be mandatory validation of the upgrade process, not a skip-able step in the plan. Therefore, we should drop this step from the plan output and integrate it into the upgrade step.

**Comment by aieri** [comment]
We could also consider dropping it from the plan output. Does showing it really add any value?

**Comment by agileshaw** [comment]
Actually, I was implying that plan should no longer contain it as a step and make it as a mandatory part of the upgrade step itself. Will rephrase the description to make it more clear.
