### ISSUE TITLE
Progress indication for upgrade sub-steps in both interactive and non-interactive mode

### ISSUE THREAD

**Issue by agileshaw** [canonical/charmed-openstack-upgrader#84]
The progress indication is only implemented for the major stages, e.g. analyzing cloud, planning cloud, and running upgrades (in non-interactive mode). As an improvement, we could additionally display in progress status for upgrade sub-steps (e.g. refresh packages, switch channels) when running in both interactive and non-interactive mode.

**Comment by aieri** [comment]
As part of this work, let's ensure that the output is resilient against users mashing the enter key. At the moment the output gets confusing:
```
Upgrade software packages of 'keystone' from the current APT repositories (c)ontinue/(a)bort/(s)kip:c




Refresh 'keystone' to the latest revision of 'ussuri/stable' (c)ontinue/(a)bort/(s)kip:Refresh 'keystone' to the latest revision of 'ussuri/stable' (c)ontinue/(a)bort/(s)kip:Refresh 'keystone' to the latest revision of 'ussuri/stable' (c)ontinue/(a)bort/(s)kip:Refresh 'keystone' to the latest revision of 'ussuri/stable' (c)ontinue/(a)bort/(s)kip:Refresh 'keystone' to the latest revision of 'ussuri/stable' (c)ontinue/(a)bort/(s)kip:c
```
